function [T] = dotmatTable(saveData)

%% Set up table

% Suppress warnings about default row contents
warning('off', 'MATLAB:table:RowsAddedExistingVars');
warning('off','MATLAB:table:RowsAddedNewVars');

tableParams = {...
    NaN,    'Trial';...
    NaN,    'CorrectionTrial';...
    NaN,    'StartTime';...
    NaN,    'CentreReward';...
    NaN,    'Modality';...
    NaN,    'TargetLoc';...
    NaN,    'HoldTime';...
    NaN,    'Atten';...
    NaN,    'StimDuration'; ...
    NaN,    'LED_V'; ...
    NaN,    'Spkr_MF'; ...
    NaN,    'LED_bgrd_V'; ...
    NaN,    'Spkr_bkgd_V'; ...
    NaN,    'ResponseLoc'; ...
    NaN,    'RespTime'; ...
    NaN,    'Correct'; ...
    
%     NaN,        'correct_trials'; ...
%     NaN,        'total_trials'; ...
%     cell(1),    'percent_correct'; ...
    };

T = table(tableParams{:,1});
T.Properties.VariableNames = tableParams(:,2);

row = 1;

for i=2:size(saveData,2)
           
    if ~isfield(saveData{1,i}, 'correct')       % gf.correct didn't exist for first few files...
        correct = 999;
    end
    
    %fill in table
    T.Trial(row,1)          = saveData{1,i}.TrialNumber-1;
    T.CorrectionTrial(row,1)= saveData{1,i}.correctionTrial;
    T.StartTime(row,1)      = saveData{1,i}.startTrialTime;
    T.CentreReward(row,1)   = saveData{1,i}.centerReward;
    T.Modality(row,1)       = saveData{1,i}.modality;       % 0=LED, 1=Speaker
    T.TargetLoc(row,1)      = saveData{1,i}.speaker;         
    T.HoldTime(row,1)       = saveData{1,i}.holdTime;
    T.Atten(row,1)          = saveData{1,i}.atten;          % Just because it's in text file.
    T.StimDuration(row,1)   = saveData{1,i}.duration;
    T.LED_V (row,1)         = saveData{1,i}.LED_stim_V;
    T.Spkr_MF(row,1)        = saveData{1,i}.Spkr_stim_MF;
    T.LED_bgrd_V(row,1)     = saveData{1,i}.LED_bgnd_V;
    T.Spkr_bkgd_V(row,1)    = saveData{1,i}.Spkr_bgnd_V;
    T.ResponseLoc(row,1)    = saveData{1,i}.response;
    T.RespTime(row,1)       = saveData{1,i}.responseTime;
    T.Correct(row,1)        = saveData{1,i}.correct;
    row = row + 1;
end

end